backend/jobs/urls.py
from django.urls import path
from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('add_job/', views.add_job, name='add_job'),
    path('add_facility/', views.add_facility, name='add_facility'),
    path('<slug>/post_job/', views.post_job, name='post_job'),
    path('<slug>/apply_job/', views.apply_job, name='apply_job'),
    path('<slug>/job_list/', views.job_list, name='job_list'),
    path('<slug>/posted_job_detail/<int:id>/',
         views.posted_job_detail, name='posted_job_detail'),
    path('<slug>/applied_job_detail/<int:id>/',
         views.applied_job_detail, name='applied_job_detail'),
    path('<slug>/list_job/', views.list_job, name='list_job'),
    path('add_skill/', views.add_skill, name='add_skill'),
    #     path('match/', views.match, name='match'),
    path('khalti/<int:id>', views.khalti, name='khalti'),
    path('search/', views.SearchView.as_view(), name='search'),
]

backend/portal/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from portal import settings
from django.urls import path, include
import jobs
import users
import room
import house
from jobs import views
from users import views
from house import views
from django.conf.urls import handler404


urlpatterns = [
    # path('chaining/', include('smart_selects.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('users/', include('users.urls')),
    path('room/', include('room.urls')),
    path('house/' , include ('house.urls')),
    path('', jobs.views.main, name='main')


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'jobs.views.error_404_view'

backend/room/urls.py
from django.urls import path
from room import views

app_name = 'room'

urlpatterns = [
    path('', views.roomtype, name='roomtype'),
    path('<int:roomtype_id>/roomlist/', views.roomlist, name='roomlist'),
    path('<int:roomtype_id>/roomlist/searchroom/', views.searchroom, name='searchroom'),
    path('<int:roomtype_id>/roomlist/postroom/', views.postroom, name='postroom'),
    path('add_facility/', views.add_facility, name='add_facility'),
    path('<int:roomtype_id>/posted_room_detail/<int:id>/', views.posted_room_detail, name='posted_room_detail'),
    path('<int:roomtype_id>/searched_room_detail/<int:id>/', views.searched_room_detail, name='searched_room_detail')

]

backend/room/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class RoomType(models.Model):
    kitchen = models.IntegerField()
    bedroom = models.IntegerField()
    hall = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together =(('kitchen', 'bedroom', 'hall'),)

    def __str__(self):
        return "Type-(Kitchen-{}, Bedroom-{}, Hall-{})".format(self.kitchen, self.bedroom, self.hall)

class Facility(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    #posted_room = models.ForeignKey(PostedRoom, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)

    class Meta:
        unique_together = (("room_type", "title"))
    
    def __str__(self):
        # return "{0}'s Skill: {1}".format(self.room_type, self.title)
        return("{0}'s Facility:{1}".format(self.room_type, self.title))


class PostedRoom(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    owner_name = models.CharField(max_length=50, null=False, blank=False)
    location = models.CharField(max_length=50, null=False, blank=False)
    conditon = models.TextField(blank=True, null=True)
    facility = models.ManyToManyField(Facility)
    price = models.CharField(max_length=100, blank=False, null=False)
    contact = models.CharField(max_length=15)
    
    def __str__(self):
        return "Posted Room in location {}".format(self.location)

    def get_facility(self):
        return "\n, ".join([f.title for f in self.facility.all()])

def get_image_filename(instance, filename):
    id = instance.posted_room.id
    return "postedroom_image/{}".format(id)

class Image(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    posted_room = models.ForeignKey(PostedRoom, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_image_filename,
                                   blank=True, null=True)

class SearchedRoom(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)
    price = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    facility = models.ManyToManyField(Facility)

    def __str__(self):
        return "Searched Room in location {}".format(self.location)




    

backend/room/forms.py
from django import forms
from .models import *

PRICE = [
    ('1', '3000-4000'),
    ('2', '4000-5000'),
    ('3', '5000-6000'),
    ('4', '6000-7000'),
    ('5', '7000-8000'),
    ('6', 'More than 8000')
]


class PostedRoomForm(forms.ModelForm):
    price = forms.ChoiceField(choices = PRICE, widget=forms.RadioSelect)

    class Meta:
        model = PostedRoom
        fields = '__all__'

class ImageForm(forms.ModelForm):
    image = forms.ImageField() 

    class Meta:
        model = Image
        fields = ('image',)

class AddFacilityForm(forms.ModelForm):
    class Meta:
        model = Facility
        fields = '__all__'

class SearchRoomForm(forms.ModelForm):
    price = forms.ChoiceField(choices = PRICE, widget=forms.RadioSelect)
    class Meta:
        model = SearchedRoom
        fields = '__all__'

backend/room/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.forms.models import modelformset_factory
from django.template import RequestContext
from django.http import HttpResponseRedirect


# Create your views here.
@login_required(login_url='/users/login/')
def roomtype(request):
    roomtype = RoomType.objects.all()
    return render(request, 'room/roomtype.html', {'roomtype':roomtype})

@login_required(login_url='/users/login/',redirect_field_name='/room/roomlist/')
def roomlist(request, roomtype_id):
    roomtype = get_object_or_404(RoomType, pk=roomtype_id)
    searchedroom = SearchedRoom.objects.filter(room_type_id = roomtype_id)
    postedroom = PostedRoom.objects.filter(room_type_id = roomtype_id)
    # image = Image.objects.all()
    context ={'searchedroom':searchedroom, 'postedroom':postedroom, 'roomtype':roomtype}
    return render(request, 'room/roomlist.html', context)

@login_required(login_url='/users/login/')
def searchroom(request, roomtype_id):
    roomtype = get_object_or_404(RoomType, pk=roomtype_id)
    facilities =  Facility.objects.all()
    if request.method == "POST":
        form = SearchRoomForm(request.POST or None)
        if form.is_valid():
            # searched_room = form.save(commit=False)
            form.save()
            return redirect('room:roomtype')
        else:
            print(form.errors)
    else:
        form = SearchRoomForm()
    
    context = {'form':form, 'roomtype':roomtype, 'facilities':facilities}
    return render(request, 'room/findroom.html', context)

@login_required(login_url='/users/login/')
def postroom(request, roomtype_id):
    # roomtype = get_object_or_404(RoomType, pk=roomtype_id)
    roomtype = get_object_or_404(RoomType, pk=roomtype_id)
    facilities =  Facility.objects.all()
    ImageFormSet = modelformset_factory(Image, fields=('image',), extra=4)
    if request.method == "POST":
        print("1")
        postedroom_form = PostedRoomForm(request.POST or None)
        # image_form = ImageForm(request.POST or None, request.FILES)
        formset = ImageFormSet(request.POST or None, request.FILES or None)
        print("2")

        if postedroom_form.is_valid() and formset.is_valid():
            print("3")


            postedroom_form.save()
            posted_room = postedroom_form.save(commit=False)
                         
            # image = image.save(commit=False)
            print("4")
            for form in formset:
                # image = form['image']
                try:
                    photo = Image(posted_room=posted_room, image=form.cleaned_data['image'])
                    photo.save()

                except Exception as e:
                    print(e)
                    print("5")

            
            

            # working without commit = False
                
            print("6")
            
            return redirect('room:roomtype')
        else:
            print(postedroom_form.errors, formset.errors)
        
    else:
        print("7")
        postedroom_form = PostedRoomForm()
        formset = ImageFormSet(queryset=Image.objects.none())
    
    context ={'roomtype':roomtype,'facilities':facilities,'postedroom_form':postedroom_form, 'formset': formset}

    return render(request, 'room/addroom.html', context)

# def postroom2(request, id):
#     room = get_object_or_404(RoomType, id=id)
   
#     facilities = Facility.objects.all()

#     ImageFormSet = modelformset_factory(Image, fields=('image',), extra=5)

#     if request.method == 'POST':

#         postedroom_form = PostedRoomForm(request.POST or None)
#         formset = ImageFormSet(request.POST or None, request.FILES or None)

#         if postedroom_form.is_valid() and formset.is_valid():
#             # postedroom = postedroom_form(commit)
#             postedroom.save()
#             for form in formset:
#                 print("1")
#                 # image = form['image']
#                 try:
#                     print("2")
#                     photo = Image(posted_room=postedroom_form, image=form.cleaned_data['image'])
#                     print("3")
#                     photo.save()
#                     print("4")
#                 except Exception as e:
#                     print("5")
#                     print(e)
           

#             return redirect('room:roomtype')
#     else:
#         print("6")
#         postedroom_form = PostedRoomForm()
#         formset = ImageFormSet(queryset=Image.objects.none())

#     context = {'room': room,
#                'formset':formset,
#                 'facilities': facilities,
#                'form': postedroom_form}
#     print("7")
#     return render(request, 'room/addroom.html', context)
        
@login_required(login_url='/users/login/')
def add_facility(request):
    if request.method == 'POST':
        form = AddFacilityForm(request.POST or None)
        if form.is_valid():
            facility = form.save(commit=False)
            facility.save()
            # messages.success(request, 'Facility added')
            return redirect(request.META['HTTP_REFERER'])
    else:
        form = AddFacilityForm()
    return render(request, 'room/add_facility.html', {'form': form})

@login_required(login_url='/users/login/')
def posted_room_detail(request, roomtype_id, id):
    roomtype = get_object_or_404(RoomType, id=roomtype_id)
    posted_room = get_object_or_404(PostedRoom.objects.order_by('-created'), id=id)
    # applied_jobs = AppliedJob.objects.get(id=id)
    print(type(int(posted_room.price)))
    price=PRICE[int(posted_room.price)][1]
    image= Image.objects.all()
    context = {'posted_room': posted_room,
               #   'applied_jobs': applied_jobs,
               'price': price,
               'roomtype': roomtype,
               'images':image,}

    return render(request, 'room/posted_room_detail.html', context)


@login_required(login_url='/users/login/')
def searched_room_detail(request, roomtype_id, id):
    roomtype = get_object_or_404(RoomType, id=roomtype_id)
    searched_room = get_object_or_404(SearchedRoom.objects.order_by('-created'), id=id)
    price=PRICE[int(searched_room.price)][1]

    # applied_jobs = AppliedJob.objects.get(id=id)

    context = {'searched_room': searched_room,
               #   'applied_jobs': applied_jobs,
               'price':price,
               'roomtype': roomtype}

    return render(request, 'room/searched_room_detail.html', context)
        

backend/templates/room/add_facility.html
{% block title %}Add Facility{% endblock %}

{% block content %}
<h2>Add Facility</h2>

<form action="{% url 'room:add_facility' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Add</button>
    <button onClick="javascript:history.go(-1);">Go back</button>
</form>

{% endblock %}

backend/templates/room/addroom.html
{% extends 'jobs/index.html' %}
{% load static %}
{% block title %} Add Room {% endblock %}

{% block content %}
{% if user.is_authenticated %}


{% if user.profile.user_type == 'Employeer'%}
<section class="eskill-banner">
	<div class="eskill-title">Features</div>
</section>

<section class="room-back">
	<div class="skill-content">
		<div>
			<h3>Fill the features below:</h3>
			<div class="row facilities">
				<form class="fill-facilities" action="{% url 'room:postroom' roomtype.id %}" method="post"
					enctype="multipart/form-data">
					{% csrf_token %}

					{% if postedroom_form.errors %}
					<span style="color: red;">{{postedroom_form.errors}}</span>
					{% endif %}
					<select name="room_type" class="form-control" required style="display:none;">
						<option value="{{roomtype.id}}"></option>
					</select>

					<select name="user" class="form-control" required style="display:none;">
						<option value="{{user.id}}"></option>
					</select>

					<div class="form-input">
						<label>Owner name</label>
						<input type="text" name="owner_name" class="form-control">
					</div>
					<div class="form-input">
						<label>Location</label>
						<input type="text" name="location" class="form-control">
					</div>
					<div class="form-input">
						<label>Conatct no.</label>
						<input type="number" name="contact" class="form-control">
					</div>

					<div class="form-input">
						<label>Condition of rooms/flats</label>
						<input type="text" name="condition" class="form-control">
					</div>
					<div class="form-input">
						<label>Facilities</label>
						{% for facility in facilities %}
						{% if facility.room_type_id == roomtype.id %}
						<div class="form-check">
							<input type="checkbox" name="facility" id="id_category" value="{{ facility.id }}">
							<label for="facility-{{facility.id}}" id="id_category"> {{ facility.title }} </label>
						</div>
						{% endif %}
						{% endfor %}
						<br>
						<span class="other"><i class="fas fa-angle-right"></i><a href="#popup1">Others</a></span>
					</div>
					<div class="form-input">
						<label>Rent price</label>
						{{ postedroom_form.price }}
					</div>
					<div class="form-input">
						<label>Upload image</label>
						{{ formset.management_form }}
						{{ formset.as_p }}

						<input type="file" id="file" name="image" accept="image/png, image/jpeg">
					</div>
					<!-- <div class="form-input">
						<label>Upload video</label>
						<input type="file" id="file" name="file" accept="video/*">
					</div> -->

			</div>

			<div class="submit-btn">
				<button type="submit" class="btn-submit">Submit</button>
			</div>
			</form>
		</div>

	</div>

	<div id="popup1" class="overlay">
		<div class="popup">
			<h4>Please enter the prefer facilities</h4>
			<a class="close" href="#">&times;</a>
			<div class="popup-content">
				<form action="{% url 'room:add_facility' %}" method="POST">
					{% csrf_token %}
					<select name="room_type" class="form-control" required style="display:none;">
						<option value="{{roomtype.id}}"></option>
					</select>
					{% if form.errors %}
					<div class="alert alert-danger">
						{{form.title.errors}}
					</div>
					{% endif %}

					<textarea name="title" required></textarea>
					<div class="more-btn"><button type="submit">Add</a></div>
				</form>
			</div>
		</div>
	</div>

</section>

{% endif %}


{% endif %}
{% endblock %}

backend/templates/room/detail.html
{% extends 'jobs/index.html' %}
{% load static %}
{% block title %} Add Room {% endblock %}

{% block content %}
{% if user.is_authenticated %}
<section class="detail-banner">
	<div class="detail-title">Detail</div>
</section>

<section class="detail">
	<div class="detail-content">
		<h3>Room details</h3>
		<div class="table-responsive">
			<table class="table">
				<tbody>
					<tr class="table-row">
						<td>Publish date</td>
						<td>:</td>
						<td>{{ room.created }}</td>
					</tr>
					<tr class="table-row">
						<td>Owner name</td>
						<td>:</td>
						<td>{{ room.owner }}</td>
					</tr>
					<tr class="table-row">
						<td>Location</td>
						<td>:</td>
						<td>{{ room.location }}</td>
					</tr>

					<tr class="table-row">
						<td>Price</td>
						<td>:</td>
						<td>{{ room.price }}</td>
					</tr>
					<tr class="table-row">
						<td>Condition of rooms/flats</td>
						<td>:</td>
						<td><span class="stext">{{ room.condition }}</span></td>
					</tr>
					<tr class="table-row">
						<td>Facilities</td>
						<td>:</td>
						<td><span class="stext">Water</span>
							<span class="stext">Electricity</span>
							<span class="stext">AC</span>
						</td>
					</tr>
					<tr class="table-row">
						<td>Rent price</td>
						<td>:</td>
						<td><span class="stext">{{room.price}}</span></td>
					</tr>
					<tr class="table-row">
						<td>Image</td>
						<td>:</td>
						<td><img src="img/esewa.png"></td>
					</tr>

				</tbody>
			</table>
		</div>
	</div>
</section>
{% endif %}
{% endblock %}

backend/templates/room/findroom.html
{% extends 'jobs/index.html' %}
{% load static %}
{% block title %} Roomlist {%endblock %}
{% block content%}
{% if user.is_authenticated %}

<section class="eskill-banner">
	<div class="eskill-title">Features</div>
</section>

<section class="skill-employer">
	<div class="skill-content">
		<div class="skill-list">
			<h3>Fill the features below:</h3>
			<div class="row facilities">
				<form class="fill-facilities" action="{% url 'room:searchroom' roomtype.id %}" method="post">
					{% csrf_token %}
					<select name="room_type" class="form-control" required style="display:none;">
						<option value="{{roomtype.id}}"></option>
					</select>

					<select name="user" class="form-control" required style="display:none;">
						<option value="{{user.id}}"></option>
					</select>
					<div class="form-input">
						<label>Rent price</label>
						{{ form.price }}
					</div>
					<div class="form-input">
						<label>Location</label>
						<input type="text" name="location" class="form-control">
					</div>
					<div class="form-input">
						<label>Facilities</label>
						{% for facility in facilities %}
						{% if facility.room_type_id == roomtype.id %}
						<div class="form-check">
							<input type="checkbox" name="facility" id="id_category" value="{{ facility.id }}">
							<label for="facility-{{facility.id}}" id="id_category"> {{ facility.title }} </label>
						</div>
						{% endif %}
						{% endfor %}
						<br>
						<span class="other"><i class="fas fa-angle-right"></i><a href="#popup1">Others</a></span>
					</div>

			</div>
			<!-- <span class="other"><i class="fas fa-angle-right"></i><a href="#popup2">Others</a></span> -->
			<div class="submit-btn">
				<button type="submit" class="btn-submit">Submit</button>
			</div>
		</div>
	</div>
	</form>

	<div id="popup1" class="overlay">
		<div class="popup">
			<h4>Please enter the prefer facilities</h4>
			<a class="close" href="#">&times;</a>
			<div class="popup-content">
				<form action="{% url 'room:add_facility' %}" method="POST">
					{% csrf_token %}
					<select name="room_type" class="form-control" required style="display:none;">
						<option value="{{roomtype.id}}"></option>
					</select>
					{% if form.errors %}
					<div class="alert alert-danger">
						{{form.title.errors}}
					</div>
					{% endif %}

					<textarea name="title" required></textarea>
					<div class="more-btn"><button type="submit">Add</a></div>
				</form>
			</div>
		</div>
	</div>

	<div id="popup2" class="overlay">
		<div class="popup">
			<h4>Please enter the prefer features</h4>
			<a class="close" href="#">&times;</a>
			<div class="popup-content">
				<form>
					<textarea name="message" id="message" rows="5"></textarea>
					<div class="more-btn"><a href="">Add</a></div>
				</form>
			</div>
		</div>
	</div>
	</form>
</section>



{% endif %}
{% endblock %}

backend/templates/room/roomlist.html
{% extends 'jobs/index.html' %}
{% load static %}
{% block title %} Roomlist {%endblock %}
{% block content%}
{% if user.is_authenticated %}

<section class="newsfeed">
  <div class="container">
    <!-- roomseeker -->
    {% if user.profile.user_type == 'Job Seeker' %}
    <div class="news-add">
      <div class="add-button"><a href="{% url 'room:searchroom' roomtype.id %}">Search</a></div>
    </div>
    {% else %}
    <div class="news-add">
      <div class="add-button">
        <a href="{% url 'room:postroom' roomtype.id %}">Add</a>
      </div>
    </div>
    {% endif %}
  </div>
  {% if user.profile.user_type == 'Job Seeker' %}
  <div class="news-content">
    <h3>Posted Rooms</h3>
    {% for room in postedroom %}
    <div class="jobseeker-list">
      <div class="js-title">{{ room.location }}located room</div>
      <div class="jsv-btn"><a href="{% url 'room:posted_room_detail' roomtype_id=roomtype.id id=room.id %}">View</a>
      </div>
    </div>
    {% endfor %}
  </div>

  {% else %}
  <div class="news-content">
    <h3>Applied Room List</h3>
    {% for room in searchedroom %}
    <div class="jobseeker-list">
      <div class="js-title">{{ room.location }} located room</div>
      <div class="jsv-btn"><a href="{% url 'room:searched_room_detail' roomtype_id=roomtype.id id=room.id %}">View</a>
      </div>
    </div>
    {% endfor %}
  </div>

  {% endif %}
</section>
{% endif %}
{% endblock %}

backend/templates/room/roomtype.html
{% extends 'jobs/index.html' %} {% load static %} {% block title %} Roomtype {% endblock %} {% block content%}
<section class="roomtype-banner">
    <div class="roomtype-title">Choose the room types</div>
</section>

<section class="room-type-all">
    <div class="container">
        <div class="row">
            <!-- <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
						<a href="">
							<div class="room-test">
							<div class="room-type green">
								<div class="room-icon"><i class="fas fa-home"></i></div>
								<div class="room-items">
			                        <div class="room-item"> 1 <i class="fas fa-bed"></i><div>Bed</div></div>
			                        <div class="room-item"> 1 <i class="fas fa-utensils"></i><div>Kitchen</div></div>
			                    </div>
							</div>
						</div>
						</a>
					</div> -->

            <!-- <a href="">
						<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
							<div class="room-test">
							<div class="room-type blue">
								<div class="room-icon"><i class="fas fa-home"></i></div>
								<div class="room-items">
			                        <div class="room-item">Single room</div>
			                    </div>
							</div>
						</div>
						</div>
					</a> -->
            {% for room in roomtype %}
            {% if room.kitchen and room.bedroom or room.kitchen and room.hall or room.hall and room.bedroom %}
            <a href="{% url 'room:roomlist' room.id %}">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="room-test">
                        <div
                            class="room-type {% if forloop.counter0|divisibleby:2 %} green {% else %} blue {% endif %}">
                            <div class="room-icon"><i class="fas fa-home"></i></div>
                            <div class="room-items">
                                {% if room.bedroom > 0 %}
                                <div class="room-item">
                                    {{ room.bedroom }} <i class="fas fa-bed"></i>
                                    <div>Bed</div>
                                </div>
                                {% endif %} {% if room.kitchen > 0 %}
                                <div class="room-item">
                                    {{ room.kitchen }} <i class="fas fa-utensils"></i>
                                    <div>Kitchen</div>
                                </div>
                                {% endif %} {% if room.hall > 0 %}
                                <div class="room-item">
                                    {{ room.hall }} <i class="fas fa-university"></i>
                                    <div>Hall</div>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            {% endif %} {% if room.hall == 0 and room.kitchen == 0 and room.bedroom == 1 %}
            <a href="{% url 'room:roomlist' room.id %}">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="room-test">
                        <div
                            class="room-type {% if forloop.counter0|divisibleby:2 %} green {% else %} blue {% endif %}">
                            <div class="room-icon"><i class="fas fa-home"></i></div>
                            <div class="room-items">
                                <div class="room-item">Single room</div>
                            </div>
                        </div>
                    </div>
                </div>

                {% endif %} {% if room.hall == 1 and room.kitchen == 0 and room.bedroom == 0 %}
                <a href="{% url 'room:roomlist' room.id %}">
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div class="room-test">
                            <div
                                class="room-type {% if forloop.counter0|divisibleby:2 %} green {% else %} blue {% endif %}">
                                <div class="room-icon"><i class="fas fa-home"></i></div>
                                <div class="room-items">
                                    <div class="room-item">Single hall</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>


                {% endif %} {% if room.hall == 0 and room.kitchen == 0 and room.bedroom > 1 %}
                <a href="{% url 'room:roomlist' room.id %}">
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div class="room-test">
                            <div
                                class="room-type {% if forloop.counter0|divisibleby:2 %} green {% else %} blue {% endif %}">
                                <div class="room-icon"><i class="fas fa-home"></i></div>
                                <div class="room-items">
                                    <div class="room-item">Multiple rooms</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %} {% if room.hall > 1 and room.kitchen == 0 and room.bedroom == 0 %}
                    <a href="{% url 'room:roomlist' room.id %}">
                        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                            <div class="room-test">
                                <div
                                    class="room-type {% if forloop.counter0|divisibleby:2 %} green {% else %} blue {% endif %}">
                                    <div class="room-icon"><i class="fas fa-home"></i></div>
                                    <div class="room-items">
                                        <div class="room-item">Multiple halls</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %} {% endfor %}

                        <!-- <a href="">
						<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
							<div class="room-test">
							<div class="room-type blue">
								<div class="room-icon"><i class="fas fa-home"></i></div>
								<div class="room-items">
			                        <div class="room-item"> 3 <i class="fas fa-bed"></i><div>Bed</div></div>
			                        <div class="room-item"> 1 <i class="fas fa-utensils"></i><div>Kitchen</div></div>
			                    </div>
							</div>
						</div>
						</div>
					</a>
					<a href="">
						<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
							<div class="room-test">
							<div class="room-type green">
								<div class="room-icon"><i class="fas fa-home"></i></div>
								<div class="room-items">
			                        <div class="room-item">Single hall</div>
			                    </div>
							</div>
						</div>
						</div>
					</a>
					<a href="">
						<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
							<div class="room-test">
							<div class="room-type blue">
								<div class="room-icon"><i class="fas fa-home"></i></div>
								<div class="room-items">
			                        <div class="room-item"> 1 <i class="fas fa-bed"></i><div>Bed</div></div>
			                        <div class="room-item"> 1 <i class="fas fa-utensils"></i><div>Kitchen</div></div>
			                        <div class="room-item"> 1 <i class="fas fa-university"></i><div>Hall</div></div>
			                    </div>
							</div>
						</div>
						</div>
					</a>
					<!-- added for testing -->

                        <!-- <a href="">
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
              <div class="room-test">
                <div class="room-type blue">
                  <div class="room-icon"><i class="fas fa-home"></i></div>
                  <div class="room-items">
                    <div class="room-item">
                      1<i class="fas fa-bed"></i>
                      <div>Bed</div>
                    </div>

                    <div class="room-item">
                      1 <i class="fas fa-utensils"></i>
                      <div>Kitchen</div>
                    </div>

                    <div class="room-item">
                      1 <i class="fas fa-university"></i>
                      <div>Hall</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </a> -->
        </div>
    </div>
</section>


{% endblock %}