backend/jobs/urls.py
from django.urls import path
from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('add_job/', views.add_job, name='add_job'),
    path('add_facility/', views.add_facility, name='add_facility'),
    path('<slug>/post_job/', views.post_job, name='post_job'),
    path('<slug>/apply_job/', views.apply_job, name='apply_job'),
    path('<slug>/job_list/', views.job_list, name='job_list'),
    path('<slug>/posted_job_detail/<int:id>/',
         views.posted_job_detail, name='posted_job_detail'),
    path('<slug>/applied_job_detail/<int:id>/',
         views.applied_job_detail, name='applied_job_detail'),
    path('<slug>/list_job/', views.list_job, name='list_job'),
    path('add_skill/', views.add_skill, name='add_skill'),
    #     path('match/', views.match, name='match'),
    path('khalti/<int:id>', views.khalti, name='khalti'),
    path('search/', views.SearchView.as_view(), name='search'),
]

backend/portal/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from portal import settings
from django.urls import path, include
import jobs
import users
import room
import house
from jobs import views
from users import views
from house import views
from django.conf.urls import handler404


urlpatterns = [
    # path('chaining/', include('smart_selects.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('users/', include('users.urls')),
    path('room/', include('room.urls')),
    path('house/' , include ('house.urls')),
    path('', jobs.views.main, name='main')


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'jobs.views.error_404_view'

backend/users/urls.py
from django.urls import path, reverse_lazy
from users import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import user_passes_test


login_forbidden = user_passes_test(lambda u: u.is_anonymous(), '/')

app_name = 'users'
urlpatterns = [
    path('login/', views.login_user, name='login_user'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('activation/', views.check_activation_code, name='activation'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html', email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done', ), from_email="DJ Group <settings.EMAIL_HOST_USER>",), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html', ), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html', success_url=reverse_lazy('users:password_reset_complete', ),),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html',), name='password_reset_complete'),
]

backend/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django import forms

from django.conf import settings
import random
from django.utils.crypto import get_random_string

# TYPES = [
#     ('Employeer', 'Employeer'),
#     ('Job Seeker', 'Job Seeker')
# ]


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    number = models.CharField(max_length=15, null=False, blank=False, unique=True)
    user_type = models.CharField(
        max_length=15, choices=[('Employeer', 'Employeer'), ('Job Seeker', 'Job Seeker')],default='Job Seeker')

    def __str__(self):
        return '{}'.format(self.user.username)

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
#
# post_save.connect(create_user_profile, sender=User,
#                   dispatch_uid="users_signal")
#
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()


def generate_activation_code():
    return (get_random_string(6, allowed_chars='0123456789'))


class ActivationCode(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    code = models.CharField(max_length=6, default=generate_activation_code)

backend/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from users.models import *

TYPES = [
    ('Employeer', 'Employeer'),
    ('Job Seeker', 'Job Seeker')
]

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    remember_me = forms.BooleanField(required=False)

    


class AddUserForm(UserCreationForm):

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError('Email Already Exists')
        return email

    class Meta:
        model = User
        fields = ['first_name','last_name','username',"email", "password1",
                  "password2"]


class ProfileForm(forms.ModelForm):
    user_type = forms.ChoiceField(choices = TYPES, widget=forms.RadioSelect)

    class Meta:
        model = Profile
        fields = ('number','user_type')

    def clean_number(self):
        number = self.cleaned_data['number']
        if Profile.objects.filter(number = number).exists():
            raise ValidationError('Phone Number Already Exists')
        return number

backend/users/views.py
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from jobs import urls
from .models import ActivationCode
from django.core.mail import send_mail
from .forms import *
from django.http import Http404
from jobs.views import dashboard
from django.views.decorators.cache import never_cache


@never_cache
def login_user(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('jobs:dashboard'))
    if request.method == 'POST':
        form = LoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            remember_me = form.cleaned_data['remember_me']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                if not remember_me:
                    request.session.set_expiry(0)
                # redirect_url = request.GET.get('next', 'users/base')
                # messages.info(request, 'You are logged in as an admin .')

                messages.success(
                    request, '{} Logged in successfully'.format(user.username))
                return redirect('main')

            # elif user and user.is_staff:
            #     login(request, user)
            #     if not remember_me:
            #         request.session.set_expiry(0)
            #     redirect_url = request.GET.get('next', 'admin:dashboard')
            #     messages.info(request, 'You are logged in as a staff member.')
            #     return redirect(redirect_url)
            elif user and not user.is_active:
                messages.info(request, 'Your account is not active now.')
            else:

                messages.error(request, 'Invalid Username or Password')

        else:

            messages.error(request, 'Invalid Form')

    else:

        form = LoginForm()

    return render(request, 'users/login.html', {'form': form})


def logout_user(request):

    if request.user.is_authenticated:
        logout(request)

        return redirect('/')


@never_cache
def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('jobs:dashboard'))
    if request.method == "POST":
        user_form = AddUserForm(request.POST or None)
        profile_form = ProfileForm(request.POST or None)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save(commit=False)
            user.is_active = False
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            code = ActivationCode.objects.create(user=user)
            send_mail(
                'Activate Your Account',
                'This is the activation code for your account: %s' % code.code,
                'DJ Group <settings.EMAIL_HOST_USER>',
                [user.email]
            )

            return render(request, 'users/activation_sent.html')

    else:
        user_form = AddUserForm()
        profile_form = ProfileForm()
    return render(request, 'users/register.html', {'user_form': user_form, 'profile_form': profile_form})


@never_cache
def check_activation_code(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('jobs:dashboard'))
    for i in ActivationCode.objects.all():
        if request.method == 'POST':
            if i.code == request.POST['activation_code']:
                i.user.is_active = True
                i.user.save()
                i.delete()

                messages.success(
                    request, 'Your account has been successfully activated. Please login to continue')
                return redirect('users:login_user')
            else:
                messages.error(request, "Please enter a valid code.")
    return render(request, 'users/activation_sent.html', {})

backend/templates/users/activation_sent.html
{% extends "users/login.html" %}

{% load static %}
{% load bootstrap3 %}

{% block content %}



<style>
    .activation {
        text-align: center;
    }

    .active-button {
        background: #005f34;
        color: #fff;
        border: none;
        padding: 7px 25px;
        border-radius: 7px;
    }

    .mtitle {
        font-size: 17px;
        margin-bottom: 10px;
    }

    .form-control {
        width: 60%;
        margin: 0 auto;
    }

    .form-content {
        width: 36%;
        margin-top: 100px;
    }
</style>

<div class="text-center" id="alert_message">

    {% bootstrap_messages %}
</div>

<div class="activation">


    <form action="{% url 'users:activation' %}" method="POST">
        {% csrf_token %}
        <label class="mtitle">Please enter activation code sent to your mail or phone to continue:</label><br>
        <input type="text" class="form-control" name="activation_code" /><br>
        <button type="submit" class="active-button">Activate</button>
</div>



{% endblock %}

backend/templates/users/login.html
{% load static %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
		integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Lexend+Deca&display=swap" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/responsive.css' %}">
</head>

<body>

	<section class="login-banner">

		<div class="login-form">
			

			<div class="form-content">
				{% block content %}
				<div class="text-center" id="alert_message">
					{% bootstrap_messages %}
				</div>
				<h3>DreamFocus</h3>
				<form action="{% url 'users:login_user' %}" method="post">
					{% csrf_token %}
					{% if form.errors %}
					
					<span style="color: red;">{{form.username.errors}}</span>
					
					{% endif %}
					<div class="form-field">
						

						<label class="test" >Username</label>
						
						
						<div class=""><input name="username" placeholder="Username/Phone Number" class="form-control" {% if form.username.value %} value="{{form.username.value}}" {% endif %} required></div>
					</div>
					{% if form.errors %}
					
					<span style="color: red;">{{form.password.errors}}</span>
					
					{% endif %}
					<div class="form-field">
						
						<label>Password</label>
						
						
						<input type="password" name="password" placeholder="Password" class="form-control" required>
					</div>
					<div class="remember">
				
						<div class="rem-right">
							<a href="{% url 'users:password_reset' %}">Forgot Password?</a>
						</div>
					</div>
					<div class="login-btn">
						<input type="submit" value="Submit" class="l-btn">
					</div>
					<div class="new-user">
						<div class="u-icon">
							<i class="fas fa-user"></i>New user ?<span><a href="{% url 'users:register' %}">Register
									here</a></span>
						</div>
					</div>
				</form>

				
{% endblock %}
			</div>

			
		</div>

	</section>
	


</body>
<script type="text/javascript">
	window.setTimeout(function () {
		$("#alert_message").fadeTo(500, 0).slideUp(500, function () {
			$(this).remove();
		});
	}, 3500);
</script>
<script src="{% static '/js/jquery.min.js' %}"></script>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
</html>

backend/templates/users/password_reset.html
{% extends 'users/login.html' %}
{% load static %}
{% load bootstrap3 %}
<title>{% block title %}Password Reset {% endblock %}</title>
{% block content %}
<div class="pt-3 h-p100">
	<div class="row h-p100 justify-content-sm-center align-items-center">
		<div>
			{% bootstrap_messages %}

			<div class="card border-info text-center">
				<div class="card-header text-center">
					<h5 style="width: 100%;">Please Enter your email to reset password</h5>

				</div>
				<div class="card-body">
					<form action="" method="post">
						{% csrf_token %}
						{% bootstrap_form form %}

						<div class="text-xs-right">
							<button type="submit" class="btn btn-info">Reset Password</button>
						</div>
					</form>
				</div>
			</div>
		</div>

	</div>
</div>
{% endblock %}

backend/templates/users/password_reset_complete.html
{% extends 'users/login.html' %}
{% load static %}
<title>{% block title %}Password Reset Complete{% endblock %}</title>
{% block content %}
<div class="container pt-3 h-p100">
	<div class="row h-p100 justify-content-sm-center align-items-center">
		<div class="col-sm-6 col-md-4">
			<div class="card border-info text-center">
				<div class="card-header text-center">
				</div>
				<div class="card-body">
					<h3>Password Changed Successfully.<a href="{% url 'users:login_user' %}" style="color:blue;"> Click
							here to login.</a></h3>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

backend/templates/users/password_reset_confirm.html
{% extends 'users/login.html' %}
{% load static %}
{% load bootstrap3 %}
<title>{% block title %}Password Reset Confirm {% endblock %}</title>
{% block content %}
	<div class="container pt-3 h-p100">
	  <div class="row h-p100 justify-content-sm-center align-items-center">
		<div class="col-sm-6 col-md-4">
		  <div class="card border-info text-center">
			<div class="card-header text-center">
                <h5 style="width: 100%;">Reset</h5>

			</div>
			<div class="card-body">
			            <form action="" method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}

					<div class="text-xs-right">
						<button type="submit" class="btn btn-info">Reset Password</button>
					</div>
                    </form>
			</div>
	  </div>
	</div>
	  </div>
	</div>

{% endblock %}

backend/templates/users/password_reset_done.html
{% extends 'users/login.html' %}
{% load static %}
{% load bootstrap3 %}
<title>{% block title %}Password Reset {% endblock %}</title>
{% block content %}
<div class="pt-3 h-p100">
  <div class="row h-p100 justify-content-sm-center align-items-center">
    <div>
      {% bootstrap_messages %}

      <div class="card border-info text-center">
        <div class="card-header">
          <h3> A password reset link has been sent to your email.Click on this link to reset your password.
          </h3>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock %}

backend/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please click on the following link and  choose a new password:" %}
{% block reset_link %}
http://{{domain}}{% url 'users:password_reset_confirm' uidb64=uid token=token  %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

The {{domain}} team {% now 'Y' %}

{% endautoescape %}

backend/templates/users/register.html
{% load static %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html>

{% block content %}

<head>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
		integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Lexend+Deca&display=swap" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static '/css/responsive.css' %}">
</head>

<body>

	


	<section class="register-banner">
		<div class="register-form">

			<div class="form-content">
				<div class="text-center" id="alert_message">
					{% bootstrap_messages %}
				</div>
				<h3>Register Form</h3>

				<form action="{% url 'users:register' %}" method="post">
					{% csrf_token %}

					
					

					<div class="form-field">

						<span class="form-field-icon"><i class="fas fa-user-alt"></i></span>
						<input type="name" name="first_name" placeholder="First name" class="form-control" {% if user_form.first_name.value %} value="{{user_form.first_name.value}}" {% endif %} required>
					</div>
					<div class="form-field">


						<span class="form-field-icon"><i class="fas fa-user-alt"></i></span>
						<input type="name" name="last_name" placeholder="Last name" class="form-control" {% if user_form.last_name.value %} value="{{user_form.last_name.value}}" {% endif %} required>
					</div>
					{% if user_form.errors %}
					
						<span style="color: red;">{{user_form.username.errors}}</span>
					
					{% endif %}
					<div class="form-field">


						<span class="form-field-icon"><i class="fas fa-user-alt"></i></span>
						<input type="name" name="username" placeholder="User name" class="form-control" {% if user_form.username.value %} value="{{user_form.username.value}}" {% endif %}>
					</div>
					{% if user_form.errors %}
					<span style="color: red;">{{user_form.email.errors}}</span>
					{% endif %}
					<div class="form-field">


						<span class="form-field-icon"><i class="fas fa-envelope"></i></span>
						<input type="email" name="email" placeholder="Email" class="form-control" {% if user_form.email.value %} value="{{user_form.email.value}}" {% endif %}>
					</div>
					{% if user_form.errors %}
					
					<span style="color: red;">{{user_form.password2.errors}}</span>
					
					{% endif %}
					<div class="form-field">


						<span class="form-field-icon"><i class="fas fa-star"></i></span>
						<input type="password" name="password1" placeholder="Password" class="form-control">
					</div>
					
					<div class="form-field">


						<span class="form-field-icon"><i class="fas fa-star"></i></span>
						<input type="password" name="password2" placeholder="Confirm Password" class="form-control">
					</div>
					{% if profile_form.errors %}
					
						<span style="color: red;">{{profile_form.number.errors}}</span>

					{% endif %}
					<div class="form-field">


						<span class="form-field-icon"><i class="fas fa-phone"></i></span>
						<input type="number" name="number" placeholder="Number" class="form-control" {% if profile_form.number.value %} value="{{profile_form.number.value}}" {% endif %}>
					</div>
					<div class="form-field">
						<span>Are you an Employeer or a Job Seeker?</span>&nbsp;&nbsp;
						<label class="job">
							{{profile_form.user_type}}</label>

					</div>
					<div class="register-btn">

						<button type="submit" class="reg-btn">Submit</button>
					</div>

				<div class="new-user">
					<div class="u-icon">
						Already a User ?<span><a href="{% url 'users:login_user' %}"> Login
								here</a></span>
					</div>
				</div>
				</form>

			</div>
		</div>
	</section>

	{% endblock %}
</body>
<script type="text/javascript">
	window.setTimeout(function () {
		$("#alert_message").fadeTo(500, 0).slideUp(500, function () {
			$(this).remove();
		});
	}, 3500);
</script>
<script src="{% static '/js/jquery.min.js' %}"></script>
<script src="{% static '/js/bootstrap.min.js' %}"></script>

</html>