backend/house/urls.py
from django.urls import path
from house import views

app_name = 'house'

urlpatterns=[

    path('', views.owner, name='owner'),
    path('buyer', views.buyer, name='buyer'),
    # path('', views.sekker, name='sekker'),
    path('house_list/', views.house_list, name='house_list'),
    path('house_list/house/<int:id>/', views.sellerhouse_detail , name='sellerhouse_detail'),
    path('house_list/home/<int:id>/', views.buyerhouse_detail , name='buyerhouse_detail'),
    path('add_facility/', views.add_facility , name='add_facility')
]

backend/jobs/urls.py
from django.urls import path
from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('add_job/', views.add_job, name='add_job'),
    path('add_facility/', views.add_facility, name='add_facility'),
    path('<slug>/post_job/', views.post_job, name='post_job'),
    path('<slug>/apply_job/', views.apply_job, name='apply_job'),
    path('<slug>/job_list/', views.job_list, name='job_list'),
    path('<slug>/posted_job_detail/<int:id>/',
         views.posted_job_detail, name='posted_job_detail'),
    path('<slug>/applied_job_detail/<int:id>/',
         views.applied_job_detail, name='applied_job_detail'),
    path('<slug>/list_job/', views.list_job, name='list_job'),
    path('add_skill/', views.add_skill, name='add_skill'),
    #     path('match/', views.match, name='match'),
    path('khalti/<int:id>', views.khalti, name='khalti'),
    path('search/', views.SearchView.as_view(), name='search'),
]

backend/portal/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from portal import settings
from django.urls import path, include
import jobs
import users
import room
import house
from jobs import views
from users import views
from house import views
from django.conf.urls import handler404


urlpatterns = [
    # path('chaining/', include('smart_selects.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('users/', include('users.urls')),
    path('room/', include('room.urls')),
    path('house/' , include ('house.urls')),
    path('', jobs.views.main, name='main')


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'jobs.views.error_404_view'

backend/house/models.py
from django.db import models
from django.contrib.auth.models import User


class Facility(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=250 , unique=True)

    def __str__(self):
        return " facility-{}".format(self.title)


class SellerPost(models.Model):
    owner_name = models.CharField(max_length=250)
    price = models.CharField(max_length=50)
    location = models.CharField(max_length=250)
    area = models.CharField(max_length=250)
    floor = models.IntegerField()
    no_of_room = models.IntegerField()
    direction_faced = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contact =  models.CharField( max_length = 120, null=True , blank=True)
    facility = models.ManyToManyField(Facility)
    

    class Meta :
        verbose_name_plural='House detail posted by Seller'
    
    def __str__(self):
        return " owner_name-{}".format(self.owner_name)

class BuyerPost(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.CharField(max_length=50 , null=True , blank=True)
    location = models.CharField(max_length=250)
    area = models.CharField(max_length=250)
    floor = models.IntegerField(null=True)
    no_of_room = models.IntegerField()
    direction_faced = models.CharField(max_length=50)
    contact =  models.CharField(max_length=120 , null=True , blank=True)
    facility = models.ManyToManyField(Facility)



    class Meta :
        verbose_name_plural='House detail posted by Buyer'
    
    def __str__(self):
        return " no_of_room-{}".format(self.no_of_room)

    
def get_image_filename(instance, filename):
    id = instance.seller_post.id
    return "sellerhouse_image/{}".format(id)

class Image(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    seller_post = models.ForeignKey(SellerPost, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_image_filename,
                                 verbose_name='Image')

class Matched(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    seller = models.ForeignKey( User , on_delete=models.CASCADE,related_name='%(class)s_seller_user_id')
    buyer = models.ForeignKey( User , on_delete=models.CASCADE,related_name='%(class)s_buyer_user_id')
    score = models.FloatField()

    class Meta:
        verbose_name_plural = 'Matches Houses '

    def __str__(self):
        return 'score-{}'.format(self.score)

backend/house/forms.py
from django import forms
from .models import *

PRICE = [
    ('0', 'Less than 20 lakhs '),
    ('1', '21-40 lakhs'),
    ('2', '41-60 lakhs'),
    ('3', '61-80 lakhs'),
    ('4', '81-99 lakhs'),
    ('5', 'More than 1 crore')
]

class SellerPostForm(forms.ModelForm):
    price = forms.ChoiceField(choices = PRICE, widget=forms.RadioSelect)

    class Meta:
        model = SellerPost
        fields = '__all__'

class BuyerPostForm(forms.ModelForm):
    price = forms.ChoiceField(choices = PRICE, widget=forms.RadioSelect)

    class Meta:
        model = BuyerPost
        fields = '__all__'

class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = Image
        fields = ('image',)

class AddFacilityForm(forms.ModelForm):
    class Meta:
        model = Facility
        fields='__all__'

backend/house/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.forms.models import modelformset_factory
from .models import *
from house.match import count,match
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required(login_url='/users/login/')
def owner(request):
    facilities = Facility.objects.all()
    c = count()
    match(c)
    ImageFormSet =modelformset_factory(Image, form=ImageForm ,extra=2)
    if request.method == "POST":
        sellerpost_form = SellerPostForm(request.POST or None)
        
        # image_form = ImageForm(request.POST or None, request.FILES)
        formset = ImageFormSet(request.POST or None , request.FILES or None)
        if sellerpost_form.is_valid() and formset.is_valid():
    
            sellerpost_form.save()
            sellerpost = sellerpost_form.save(commit=False)
            
            for form in formset:
                try: 
                    photo = Image(seller_post=sellerpost , image =form.cleaned_data['image'])
                    
                    photo.save()
                except Exception as e:
                    print(e)
            

            return redirect('main')
                
        else:
            print(sellerpost_form.errors , formset.errors)

    else:
        sellerpost_form =SellerPostForm()
        formset = ImageFormSet(queryset=Image.objects.none())
    return render(request, 'house/ofeatures.html', 
    {'sellerpost_form':sellerpost_form,'formset':formset , 'facilities': facilities})

@login_required(login_url='/users/login/')

def buyer(request):
    facilities = Facility.objects.all()

    if request.method == "POST":
        buyerpost_form = BuyerPostForm(request.POST or None)
     
        if buyerpost_form.is_valid():
    
            # buyerpost = buyerpost_form.save(commit=False)
            buyerpost_form.save()
        
        
            return redirect('main')

        else:
            
            print(buyerpost_form.errors )

    else:
       
        buyerpost_form = BuyerPostForm()
        
    return render(request, 'house/ofeatures.html', 
    {'buyerpost_form':buyerpost_form ,'facilities':facilities} )


@login_required(login_url='/users/login/')

def house_list(request):
    seller= SellerPost.objects.all()
    buyer = BuyerPost.objects.all()

    return render(request, 'house/onewsfeed.html',
     { 'seller' :seller , 'buyer' : buyer })

def sellerhouse_detail (request, id ):
    house = get_object_or_404(SellerPost, id=id)
    print(house)
    price=PRICE[int(house.price)][1]
    images=  Image.objects.all()

    return render(request, 'house/seller_detail.html',
                    { 'house': house , 'price': price , 'images':images})

def buyerhouse_detail(request , id ):

    home = get_object_or_404(BuyerPost, id=id)
    price=PRICE[int(home.price)][1]
    return render(request, 'house/buyer_detail.html',
    { 'home': home , 'price': price})

def add_facility(request):
    if request.method == 'POST':
        form = AddFacilityForm(request.POST or None)
        if form.is_valid():
            facility =form.save(commit=False)
            facility.save()

            return redirect(request.META['HTTP_REFERER'])

        else:
            form =AddFacilityForm()

        return render(request , 'house/add_facility.html', {'form': form})

def email_match(recipient, text):
    subject = 'Match Found'
    send_mail(subject, text,'DJ Group <settings.EMAIL_HOST_USER>', recipient)
              
def email(recipient, text):
    subject = 'Contact Detail'

    send_mail(subject, text,
              'DJ Group <settings.EMAIL_HOST_USER>', recipient)
    return redirect('/')
        
    
        

backend/templates/house/add_facility.html
<h2> ADD Facility </h2>

<form action ="{% url 'house:add_facility' %}" method="POST">

    {% csrf_token %}
    {{ form.as_P}}
    <button type="submit">ADD</button>
    <button onclick="javascript:history.go(-1);">
        GO back</button>
</form>

backend/templates/house/booking.html
<!DOCTYPE html>
<html>
	<head>
		<title>Home/Booking</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="css/style.css">
		<link rel="stylesheet" type="text/css" href="css/jsbooking.css">
		<link rel="stylesheet" type="text/css" href="css/responsive.css">
	</head>
	<body>
		<header class="head">
			<div class="container">
				<div class="row">
					<div class="header-left">
						<div class="col-lg-6 col-md-6 col-sm-6 col-xs-4">
							<a href="" class="logo"><img src="img/logo.png"></a>
						</div>
					</div>
					<div class="header-right">
						<div class="col-lg-6 col-md-6 col-sm-6 col-xs-8">
							<ul class="formclick">
								<li><a href="">Post</a></li>
								<li><i class="fas fa-lock"></i><a href="register.html">Register</a></li>
								<li><i class="fas fa-user"></i><a href="login.html">Login</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</header>

		<section class="booking-banner">
			<div class="booking-title">Booking</div>
		</section>

		<section class="booking-form">
			<div class="booking-content">
				<div class="booking-field">
					<div class="bill-icon">
						<i class="fas fa-info"></i><b>Billing details</b>
					</div>
					<form>
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="booking-field">
									<label>Firstname<span class="red">*</span></label>
									<input type="text" name="text" placeholder="First name" class="form-control">
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<label>Lastname<span class="red">*</span></label>
								<div class="booking-field">
									<input type="text" name="text" placeholder="Last name" class="form-control">
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="booking-field">
									<label>Email</label>
									<input type="email" name="email" placeholder="Email" class="form-control">
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<label>Mobile number<span class="red">*</span></label>
								<div class="booking-field">
									<input type="number" name="number" placeholder="Mobile Number" class="form-control">
								</div>
							</div>
						</div>
					</form>
				</div>
				<div class="booking-list">
					<div class="order-icon">
						<i class="fas fa-shopping-cart"></i><b>Your order</b>
					</div>
					<div class="table-responsive">
						<table class="table">
							<tbody>
								<tr>
									<th class="jname">Home location</th>
									<th class="jname">Total</th>
								</tr>
								<tr>
									<td>Kathmandu</td>
									<td>$10</td>
								</tr>
								<tr>
									<td><b>Total</b></td>
									<td><b>$10</b></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="booking-type">
					<div class="booking-icon">
						<div class="e-icon">
							<div class="icon-img"><a href="https://esewa.com.np/"><img src="img/esewa.png"></a></div>
							<div class="icon-name">Esewa</div>
						</div>
						<div class="k-icon">
							<div class="icon-img"><a href="https://khalti.com/"><img src="img/khalti.png"></a></div>
							<div class="icon-name">Khalti</div>
						</div>
						<div class="i-icon">
							<div class="icon-img"><a href="http://www.imepay.com.np/"><img src="img/ime.png"></a></div>
							<div class="icon-name">Ime pay</div>
						</div>
					</div>
				</div>
				<div class="billing-btn">
					<input type="submit" name="place" value="Place order" class="place-btn">
				</div>
			</div>
		</section>

		

		<section class="footer">	
			<div class="container">
				<div class="footer-part">
					<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
						<div class="footer-term">
							<h4 class="ft-title">Who we are</h4>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet quam eu purus rutrum suscipit eget ac lacus. Donec vel euismod odio. Suspendisse consectetur quis risus sit amet aliquam.</p>
						</div>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
						<div class="footer-term">
							<h4 class="ft-title">Home seeker</h4>
							<ul class="ft-list">
								<li class="ft-item"><i class="fas fa-angle-right"></i><a href="register.html">Register</a></li>
								<li class="ft-item"><i class="fas fa-angle-right"></i><a href="login.htm">Login</a></li>
								<li class="ft-item"><i class="fas fa-angle-right"></i><a href="">Search land</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
						<div class="footer-term">
							<h4 class="ft-title">Home owner</h4>
							<ul class="ft-list">
								<li class="ft-item"><i class="fas fa-angle-right"></i><a href="register.html">Register</a></li>
								<li class="ft-item"><i class="fas fa-angle-right"></i><a href="login.html">Login</a></li>
								<li class="ft-item"><i class="fas fa-angle-right"></i><a href="">Post</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
						<div class="footer-term">
							<h4 class="ft-title">Contact us</h4>
							<ul class="link">
								<li><i class="fas fa-home"></i>Bhatbhateni, Koteswor</li>
								<li><i class="fas fa-envelope"></i>info@djgroup.com</li>
								<li><i class="fas fa-phone"></i>+9840236521</li>
								<li><i class="fas fa-globe"></i><a href="">http://www.djgroup.com</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</section>
	</body>
	<script src="js/jquery.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script type="text/javascript">
	$(window).scroll(function(){
    if ($(window).scrollTop() >= 50) {
        $('.head').addClass('header-fixed');
    }
    else {
        $('.head').removeClass('header-fixed');
    }
});
</script>
</html>

backend/templates/house/buyer_detail.html
{% extends 'jobs/index.html' %}
{% load static %}
{% block title %}{% endblock %}

{% block content %}

	<section class="detail-banner">
		<div class="detail-title">Detail</div>
	</section>

	<section class="detail">
		<!-- <div class="detail-content">
			<div class="skill-field">
				<span>MySql</span>
				<span>Database</span>
				<span>Photoshop</span>
			</div>
			<div class="facility-field">
				<span></span>
			</div>
			<div class="experiance-field">
				
			</div>
		</div> -->
		<div class="detail-content">
			<h3>Home details</h3>
			<div class="table-responsive">
				<table class="table">
				<tbody>
					<tr class="table-row">
						<td>Price</td>
						<td>:</td>
						<td>{{ price }}</td>
					</tr>
					<tr class="table-row">
						<td>Area</td>
						<td>:</td>
						<td>{{ home.area }}</td>
					</tr>
					<tr class="table-row">
						<td>Stored</td>
						<td>:</td>
						<td>{{ home.floor}}</td>
					</tr>
					<tr class="table-row">
						<td>Location</td>
						<td>:</td>
						<td><span class="stext">{{ home.location}}</span></td>
					</tr>
					<tr class="table-row">
						<td>No. of room</td>
						<td>:</td>
						<td>{{ home.no_of_room }}</td>
					</tr>
					<tr class="table-row">
						<td>Direction faced</td>
						<td>:</td>
						<td>{{ home.direction_faced }}</td>
					</tr>
					<tr class="table-row">
						<td>Conatct</td>
						<td>:</td>
						<td>{{ home.contact }}</td>
					</tr>
					<!-- {% if user.profile.user_type == 'Job Seeker' %}
					<tr class="table-row">
						<td>Images</td>
						<td>:</td>
						<td>
						{% for image in images %}
						
						{% if image.seller_post.id == house.id %}
						
						<img style="height: 150px ; width:auto ;" src="/media/{{image.image}}">
						&nbsp;&nbsp;&nbsp;
						{% endif %}
						{% endfor %}
						</td>
					</tr>
					{% endif %} -->
				</tbody>
				</table>
			</div>
		</div>
	</section>


	{% endblock %}

backend/templates/house/ofeatures.html
{% extends 'jobs/index.html' %}
{% load static %}
{% load bootstrap3 %}
{% block title %} {% endblock %}

{% block content %}

{% if user.is_authenticated %}
	{% if user.profile.user_type == 'Employeer' %}
	<section class="eskill-banner">
		<div class="eskill-title">Features</div>
	</section>
	<div class="news-add">
			<div class="add-button"><a href="{% url 'house:house_list' %} ">View List</a></div>
		</div>
	<section class="skill-employer">
		<div class="skill-content">
			<div class="skill-list">
				<h3>Fill the House Detail:</h3>
				<div class="row facilities">
					{{ sellerpost_form.errors }}
					<form class="fill-facilities" action="{% url 'house:owner' %}" method="post"  enctype="multipart/form-data">
						{% csrf_token %}
							<div class="form-input">
									<label>Owner name</label>
									<input type="text" name="owner_name" class="form-control">
								</div>
								<select name="user" class="form-control" required style="display:none;">
									<option value="{{user.id}}"></option>
								</select>		
						<div class="form-input">
							<label>Price</label>
								{{sellerpost_form.price}}
							<!-- <input type="number" name="price" class="form-control"> -->
						</div>
						<div class="form-input">
							<label>Location</label>
							<input type="text" name="location" class="form-control">
						</div>
						<div class="form-input">
							<label>Area</label>
							<input type="text" name="area" class="form-control">
						</div>
						<div class="form-input">
							<label>No of floors</label>
							<input type="number" name="floor" class="form-control">
						</div>
						<div class="form-input">
							<label>No of rooms</label>
							<input type="text" name="no_of_room" class="form-control">
						</div>
						<div class="form-input">
							<label>Direction Faced</label>
							<input type="text" name="direction_faced" class="form-control">
						</div>
						<div class="form-input">
							<label>Contact</label>
							<input type="text" name="contact" class="form-control">
						</div>
						<div class="form-input">
							<label>Facilities</label>
							{% for facility in facilities %}
							<div class="form-check">

							<input type="checkbox" name="facility" id="id_category" value="{{ facility.id}}">
							<label for="facility-{{facility.id}}" id="id_category ">{{ facility.title}}</label>
							</div>
						
							{% endfor %}
							<br>
							<span class="other"> <i class="fas fa-angle-right"></i><a href="#popup1">Others</a></span>

						</div>
						<div class="form-input">
							<label>Upload image</label>
						

							
							{{ formset.management_form}}
							{{ formset.as_p}}
						</div>
						<!-- <div class="form-input">
							<label>Upload video</label>
							<input type="file" id="file" name="file" accept="video/*">
						</div>
					 -->
				</div>
							<div class="submit-btn">
					<button type="submit" class="btn-submit">Submit</button>
				</div>
			</form>
			</div>
		</div>
		<div id="popup1" class="overlay">
			<div class="popup">
				<h4>Please enter the prefer facilities</h4>
				<a class="close" href="#">&times;</a>
				<div class="popup-content">
					<form action="{% url 'house:add_facility' %}" method="POST" >
						{% csrf_token %}
						{% if form.error %}
						<div class='alert alert-danger'>
							{{ form.title.error}}
						</div>
						{% endif %} 
						<textarea name="title" required></textarea>
						<div class="more-btn"><button type="submit">Add</div>
					</form>
				</div>
			</div>
		</div>
	</section>
	
	{% else %}
	<!-- <section class="eskill-banner">
		<div class="eskill-title">Features</div>
	</section> -->
	<div class="news-add">
			<div class="add-button"><a href="{% url 'house:house_list' %} ">View List</a></div>
		</div>
	<section class="skill-employer">
		<div class="skill-content">
			<div class="skill-list">
				<h3>Fill the required house detail :</h3>
				<div class="row facilities">
					<form class="fill-facilities" action="{% url 'house:buyer' %}" method="post" >
						{% csrf_token %}
						<div class="form-input">
							<label>Price</label>
								{{ sellerpost_form.price }}
							<!-- <input type="number" name="price" class="form-control"> -->
						</div>
						<select name="user" class="form-control" required style="display:none;">
							<option value="{{user.id}}"></option>
						</select>
						<div class="form-input">
							<label>Location</label>
							<input type="text" name="location" class="form-control">
						</div>
						<div class="form-input">
							<label>Area</label>
							<input type="text" name="area" class="form-control">
						</div>
						<div class="form-input">
							<label>No of floors</label>
							<input type="number" name="floor" class="form-control">
						</div>
						<div class="form-input">
							<label>No of rooms</label>
							<input type="text" name="no_of_room" class="form-control">
						</div>
						<div class="form-input">
							<label>Direction Faced</label>
							<input type="text" name="direction_faced" class="form-control">
						</div>
						<div class="form-input">
							<label>Contact</label>
							<input type="text" name="contact" class="form-control">
						</div>
						<div class="form-input">
								<label>Facilities</label>
								{% for facility in facilities %}
								<div class="form-check">
	
								<input type="checkbox" name="facility" id="id_category" value="{{ facility.id}}">
								<label for="facility-{{facility.id}}" id="id_category ">{{ facility.title}}</label>
								</div>
							
								{% endfor %}
								<br>
								<span class="other"> <i class="fas fa-angle-right"></i><a href="#popup1">Others</a></span>
	
							</div>
						<div class="submit-btn">
							<button type="submit" class="btn-submit">Submit</button>
						</div>
					</form>
					<div id="popup1" class="overlay">
							<div class="popup">
								<h4>Please enter the prefer facilities</h4>
								<a class="close" href="#">&times;</a>
								<div class="popup-content">
									<form action="{% url 'house:add_facility' %}" method="POST" >
										{% csrf_token %}
										{% if form.error %}
										<div class='alert alert-danger'>
											{{ form.title.error}}
										</div>
										{% endif %} 
										<textarea name="title" required></textarea>
										<div class="more-btn"><button type="submit">Add</div>
									</form>
								</div>
							</div>
						</div>
				</div>
				
			</div>
		</div>

		
	</section>


	
	{% endif %}
	{% endif %}

{% endblock %}

	


	

backend/templates/house/onewsfeed.html
{% extends 'jobs/index.html' %}
{% load static %}
{% load bootstrap3 %}
{% block title %}{% endblock %}

{% block content %}

	<!-- <section class="news-banner">
		<div class="news-title">Newsfeed</div>
	</section> -->
	{% if user.is_authenticated %}
	<section class="newsfeed">
		<div class="container">
			<div class="news-add">
				<div class="add-button"><a href="">Add</a></div>
			</div>
		</div>
		
	{% if user.profile.user_type == 'Employeer' %}
		<div class="news-content">
			<h3>Home seeker features list</h3>
			{% for b in buyer  %}
			<div class="jobseeker-list" >
		
				<div class="js-title">{{b.floor}} 'r floor house</div>
				<div class="jsv-btn"><a href="{% url 'house:buyerhouse_detail' b.id %}">View</a></div>
			</div>
			{% endfor %}
			
		</div>
	</section>
	{% else %}
	<div class="news-content">
			<h3>Home Owner features list</h3>
			{% for s in seller %}

			<div class="jobseeker-list">
				<div class="js-title">{{ s.floor}} 'r floor house</div>
				<div class="jsv-btn"><a href="{% url 'house:sellerhouse_detail' s.id %}">View</a></div>
			</div>
			{% endfor %}
		</div>
	</section>
	{% endif %}
	{% endif %}
	{% endblock %}


	

backend/templates/house/seller_detail.html
{% extends 'jobs/index.html' %}
{% load static %}
{% block title %}{% endblock %}

{% block content %}

	<section class="detail-banner">
		<div class="detail-title">Detail</div>
	</section>

	<section class="detail">
		<!-- <div class="detail-content">
			<div class="skill-field">
				<span>MySql</span>
				<span>Database</span>
				<span>Photoshop</span>
			</div>
			<div class="facility-field">
				<span></span>
			</div>
			<div class="experiance-field">
				
			</div>
		</div> -->
		<div class="detail-content">
			<h3>Home details</h3>
			<div class="table-responsive">
				<table class="table">
				<tbody>
					<tr class="table-row">
						<td>Price</td>
						<td>:</td>
						<td>{{ price }}</td>
					</tr>
					<tr class="table-row">
						<td>Area</td>
						<td>:</td>
						<td>{{ house.area }}</td>
					</tr>
					<tr class="table-row">
						<td>Stored</td>
						<td>:</td>
						<td>{{ house.floor}}</td>
					</tr>
					<tr class="table-row">
						<td>Location</td>
						<td>:</td>
						<td><span class="stext">{{ house.location}}</span></td>
					</tr>
					<tr class="table-row">
						<td>No. of room</td>
						<td>:</td>
						<td>{{ house.no_of_room }}</td>
					</tr>
					<tr class="table-row">
						<td>Direction faced</td>
						<td>:</td>
						<td>{{ house.direction_faced }}</td>
					</tr>
					<tr class="table-row">
						<td>Conatct</td>
						<td>:</td>
						<td>{{ house.contact }}</td>
					</tr>
					<!-- {% if user.profile.user_type == 'Job Seeker' %} -->
					<tr class="table-row">
						<td>Images</td>
						<td>:</td>
						<td>
						{% for image in images %}
						
						{% if image.seller_post.id == house.id %}
						
						<img style="height: 150px ; width:auto ;" src="/media/{{image.image}}">
						&nbsp;&nbsp;&nbsp;
						{% endif %}
						{% endfor %}
						</td>
					</tr>
					<!-- {% endif %} -->
				</tbody>
				</table>
			</div>
		</div>
	</section>


	{% endblock %}