backend/jobs/urls.py
from django.urls import path
from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('add_job/', views.add_job, name='add_job'),
    path('add_facility/', views.add_facility, name='add_facility'),
    path('<slug>/post_job/', views.post_job, name='post_job'),
    path('<slug>/apply_job/', views.apply_job, name='apply_job'),
    path('<slug>/job_list/', views.job_list, name='job_list'),
    path('<slug>/posted_job_detail/<int:id>/',
         views.posted_job_detail, name='posted_job_detail'),
    path('<slug>/applied_job_detail/<int:id>/',
         views.applied_job_detail, name='applied_job_detail'),
    path('<slug>/list_job/', views.list_job, name='list_job'),
    path('add_skill/', views.add_skill, name='add_skill'),
    #     path('match/', views.match, name='match'),
    path('khalti/<int:id>', views.khalti, name='khalti'),
    path('search/', views.SearchView.as_view(), name='search'),
]

backend/land/urls.py
from django.urls import path
from land import views

app_name = 'land'

urlpatterns = [
    path('searchland/', views.landformbuy, name='landformbuy'),
    path('postland/', views.landformsell, name='landformsell'),
    path('add_facility/', views.add_facility, name='add_facility'),

]

backend/portal/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from portal import settings
from django.urls import path, include
import jobs
import users
import room
import house
from jobs import views
from users import views
from house import views
from django.conf.urls import handler404


urlpatterns = [
    # path('chaining/', include('smart_selects.urls')),
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('users/', include('users.urls')),
    path('room/', include('room.urls')),
    path('house/' , include ('house.urls')),
    path('', jobs.views.main, name='main')


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'jobs.views.error_404_view'

backend/room/urls.py
from django.urls import path
from room import views

app_name = 'room'

urlpatterns = [
    path('', views.roomtype, name='roomtype'),
    path('<int:roomtype_id>/roomlist/', views.roomlist, name='roomlist'),
    path('<int:roomtype_id>/roomlist/searchroom/', views.searchroom, name='searchroom'),
    path('<int:roomtype_id>/roomlist/postroom/', views.postroom, name='postroom'),
    path('add_facility/', views.add_facility, name='add_facility'),
    path('<int:roomtype_id>/posted_room_detail/<int:id>/', views.posted_room_detail, name='posted_room_detail'),
    path('<int:roomtype_id>/searched_room_detail/<int:id>/', views.searched_room_detail, name='searched_room_detail')

]

backend/users/urls.py
from django.urls import path, reverse_lazy
from users import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import user_passes_test


login_forbidden = user_passes_test(lambda u: u.is_anonymous(), '/')

app_name = 'users'
urlpatterns = [
    path('login/', views.login_user, name='login_user'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('activation/', views.check_activation_code, name='activation'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html', email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done', ), from_email="DJ Group <settings.EMAIL_HOST_USER>",), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html', ), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html', success_url=reverse_lazy('users:password_reset_complete', ),),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html',), name='password_reset_complete'),
]

backend/jobs/forms.py
from django import forms
from .models import *


class AddJobTypeForm(forms.ModelForm):
    class Meta:
        model = JobType
        fields = '__all__'


class AddSkillForm(forms.ModelForm):
    class Meta:
        model = Skills
        fields = '__all__'


class AddFacilityForm(forms.ModelForm):
    class Meta:
        model = Facility
        fields = '__all__'


class AddPostedJobForm(forms.ModelForm):
    class Meta:
        model = PostedJob
        fields = '__all__'

class AddAppliedJobForm(forms.ModelForm):
    class Meta:
        model = AppliedJob
        fields = '__all__'


# class PaymentForm(forms.ModelForm):
#     class Meta:
#         model = Payment
#         fields = '__all__'

backend/jobs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.urls import reverse
from .forms import *
from .models import *
from jobs.match import count, match
from jobs.exchange import exchange, verify
from jobs.khalti import *
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
import requests
from django.http import JsonResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
import json
import re
import datetime
from django.db.models import Q
from itertools import chain
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    profile = Profile.objects.all()
    job_types = JobType.objects.all()
    # path = request.get_full_path()[2:]
    
    # if 'oid' in path:
    #     data = re.split('oid=+|&amt=+|\&refId=', path)
    #     del data[0]
    #     url ="https://uat.esewa.com.np/epay/transrec"
    #     d = {
    #         'amt': data[1],
    #         'scd': 'NP-ES-EPAY',
    #         'rid': data[2],
    #         'pid': data[0],
    #     }
    #     resp = requests.post(url, d)
    #     print(resp.text)
    #     test = []
    #     for i in Payment.objects.all():
    #         test.append((i.profile_id, i.name, i.amount,  i.mobile))
    #     if (request.user.id, request.user.username, data[1], request.user.profile.number) not in test:
    #         paid = Payment()
    #         paid.profile_id = request.user.id
    #         paid.name = request.user.username
    #         paid.amount = data[1]
    #         for temp in JobType.objects.filter(id = data[0]):
    #             paid.product = temp.title
    #         paid.mobile = request.user.profile.number
    #         paid.created_on = datetime.datetime.now()
    #         paid.save()
    

    context = {'profile': profile, 'job_types': job_types}
    return render(request, 'jobs/index.html', context)


def main(request):
    return render(request, 'jobs/main.html')

def dashboard(request):
    job_types = JobType.objects.all()
    path = request.get_full_path()[2:]
    
    if 'oid' in path:
        data = re.split('oid=+|&amt=+|\&refId=', path)
        del data[0]
        url ="https://uat.esewa.com.np/epay/transrec"
        d = {
            'amt': data[1],
            'scd': 'NP-ES-EPAY',
            'rid': data[2],
            'pid': data[0],
        }
        resp = requests.post(url, d)
        print(resp.text)
        test = []
        for i in Payment.objects.all():
            test.append((i.profile_id, i.name, i.amount,  i.mobile))
        if (request.user.id, request.user.username, data[1], request.user.profile.number) not in test:
            paid = Payment()
            paid.profile_id = request.user.id
            paid.name = request.user.username
            paid.amount = data[1]
            
            pid = data[0]
            p = int(pid[0])
           
            for temp in JobType.objects.filter(id = p):
                paid.product = temp.id
            paid.mobile = request.user.profile.number
            paid.created_on = datetime.datetime.now()
            paid.save()

    c = count()
    match(c)

    verify()
    exchange()

    context = {'job_types': job_types}
    return render(request, 'jobs/dashboard.html', context)


@login_required
def add_job(request):
    if request.method == 'POST':
        form = AddJobTypeForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Job Added')

            return redirect('jobs:add_job')
    else:
        form = AddJobTypeForm()

    return render(request, 'jobs/add_job.html', {'form': form})


@login_required
def post_job(request, slug):
    type = get_object_or_404(JobType, slug=slug)
    skills = Skills.objects.all()

    facilities = Facility.objects.all()
    # selected_skill = Skills.objects.filter(
    #     id__in=request.POST.getlist('skill'))
    # print(selected_skill)
    # selected_facility = Facility.objects.filter(
    #     id__in=request.POST.getlist('facility'))
    # print(selected_facility)
    if request.method == 'POST':

        form = AddPostedJobForm(request.POST or None)

        if form.is_valid():

            form.save()
            messages.success(request, 'Job Posted')

            return redirect('jobs:dashboard')
    else:
        form = AddPostedJobForm()

    context = {'type': type,
               'skills': skills,

               'facilities': facilities,
               'form': form}

    return render(request, 'jobs/apply_job.html', context)


@login_required
def apply_job(request, slug):
    type = get_object_or_404(JobType, slug=slug)
    skills = Skills.objects.all()
    facilities = Facility.objects.all()
    if request.method == 'POST':
        form = AddAppliedJobForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Job Applied')

            return redirect('jobs:dashboard')
    else:
        form = AddAppliedJobForm()
    context = {'type': type,
               'skills': skills,
               'facilities': facilities,
               'form': form}
    return render(request, 'jobs/apply_job.html', context)


@login_required
def list_job(request, slug):
    type = get_object_or_404(JobType, slug=slug)
    posted_jobs = PostedJob.objects.all()
    context = {'posted_jobs': posted_jobs, 'type': type}
    return render(request, 'jobs/list_job.html', context)


@login_required
def add_facility(request):
    if request.method == 'POST':
        form = AddFacilityForm(request.POST or None)
        if form.is_valid():
            facility = form.save(commit=False)
            facility.save()
            # messages.success(request, 'Facility added')
            return redirect(request.META['HTTP_REFERER'])
    else:
        form = AddFacilityForm()
    return render(request, 'jobs/add_facility.html', {'form': form})


@login_required
def add_skill(request):

    if request.method == 'POST':
        form = AddSkillForm(request.POST or None)
        if form.is_valid():
            form.save()

        # messages.success(request, 'Skill Added Successfully')
        return redirect(request.META['HTTP_REFERER'])
    else:
        form = AddSkillForm()

    return render(request, 'jobs/add_skill.html', {'form': form})


@login_required
def job_list(request, slug):
    type = get_object_or_404(JobType, slug=slug)

    posted_jobs = PostedJob.objects.all().order_by('-created')
    applied_jobs = AppliedJob.objects.all().order_by('-created')

    context = {'posted_jobs': posted_jobs,
               'applied_jobs': applied_jobs,
               'type': type}

    return render(request, 'jobs/job_list.html', context)


@login_required
def posted_job_detail(request, slug, id):
    type = get_object_or_404(JobType, slug=slug)
    posted_jobs = get_object_or_404(
        PostedJob.objects.order_by('-created'), id=id)
    # applied_jobs = AppliedJob.objects.get(id=id)

    context = {'posted_jobs': posted_jobs,
               #   'applied_jobs': applied_jobs,
               'type': type}

    return render(request, 'jobs/posted_job_detail.html', context)


@login_required
def applied_job_detail(request, slug, id):
    type = get_object_or_404(JobType, slug=slug)
    # posted_jobs = PostedJob.objects.get(id=id)
    applied_jobs = get_object_or_404(
        AppliedJob.objects.order_by('-created'), id=id)

    context = {  # 'posted_jobs': posted_jobs,
        'applied_jobs': applied_jobs,
        'type': type}

    return render(request, 'jobs/applied_job_detail.html', context)


def email_match(recipient, text):
    subject = 'Match Found'
    send_mail(subject, text,
              'DJ Group <settings.EMAIL_HOST_USER>', recipient)


def email(recipient, text):
    subject = 'Contact Detail'
    
    send_mail(subject, text,
              'DJ Group <settings.EMAIL_HOST_USER>', recipient)
    return redirect('/')


def sms(number, text):
    r = requests.post(
            "http://api.sparrowsms.com/v2/sms/",
            data={'token' : 'I53mEFe0oi8oOC0BrMLv',
                  'from'  : 'Demo',
                  'to'    : number,
                  'text'  : text})
    

    status_code = r.status_code
    # response = r.text
    response_json = r.json()
    print(status_code)
    # print(response)
    print(response_json)
    return r


@csrf_exempt
def khalti(request, id):
    person = User.objects.all()
    match = get_object_or_404(Match, id=id)

    applied = AppliedJob.objects.all()
    posted = PostedJob.objects.all()
    

    if request.method == "POST" and request.is_ajax():

        token = request.POST['token']
        amount = request.POST['amount']
        # user_id = request.POST['product_identity']
        product = request.POST['product_identity']

        v = verification(token, amount)

        if v['state']['name'] == "Completed":
            print("Completed")
            paid = Payment()
            paid.profile_id = request.user.id
            paid.name = v['user']['name']
            paid.amount = int(v['amount']) / 100
            paid.mobile = v['user']['mobile']
            paid.created_on = v['created_on']
            paid.product = int(product)
            paid.save()

   

                        # url2 = "https://khalti.com/api/v2/merchant-transaction/"
                        # t = transaction_list(url2)

                        # print(v)
                        # for i in t['records']:
                        #     print(i['amount'])
                        #     print(i['user']['name'])
                        #     print(i['user']['mobile'] + "\n")
                        # print(t[''])

backend/templates/jobs/apply_job.html
{% extends 'jobs/index.html' %}
{% load static %}
{% load bootstrap3 %}
{% block title %}{% endblock %}

{% block content %}


{% if user.is_authenticated %}
{% if user.profile.user_type == 'Job Seeker' %}


<div class="text-center" id="alert_message">
    {% bootstrap_messages %}
</div>

<section class="image-back">
    <div class="form-heading">
        <h2>Apply for the job</h2>
    </div>

    <div class="skill-content">
        <div class="skill-list">



            <form action="{% url 'jobs:apply_job' type.slug %}" method="post">
                {% csrf_token %}

                {% if form.errors %}
                <span style="color: red;">{{form.skills.errors}}</span>
                {% endif %}

                <div class="choose-skill">
                    <h3>Choose the below skills:</h3>
                    <div class="row skills">
                        <div class="col-md-12 col-sm-12 col-xs-12 list-img">


                            {% for skill in skills %}
                            {% if skill.job_type_id == type.id %}
                            <div class="form-check">
                                <input type="checkbox" name="skills" id="skill-{{skill.id}}" value="{{skill.id}}">
                                <label for="skill-{{ skill.id }}">{{skill.title}}</label>
                            </div>
                            {% endif %}
                            {% endfor %}
                            <span class="other"><i class="fas fa-angle-right"></i><a href="#popup1">Others</a></span>

                        </div>

                    </div>
                </div>

                <div class="facility-all">
                    <div class="row facilities">
                        <div class="form-input">

                            <select name="user" required class="form-control" style="display: none;">
                                <option value="{{user.id}}">{{user.username}}</option>
                            </select>

                        </div>
                        <div class="form-input">

                            <select name="job_type" class="form-control" required style="display: none;">
                                <option value="{{type.id}}">{{type.title}}</option>
                            </select>

                        </div>


                        <div class="form-input">
                            <label>Address</label>

                            {% if form.errors %}
                            <span style="color: red;">{{form.location.errors}}</span>
                            {% endif %}

                            <input type="text" name="location" class="form-control" {% if form.location.value %}
                                value='{{form.location.value}}' {% endif %} required>
                        </div>
                    </div>
                </div>
                <!-- <div class="experiance red">
                    <h3>Your experience in this field</h3>

                    <div class="slidecontainer">
                        <input type="range" name="experience" min="1" max="10" value="1" class="slider" id="range">
                        <p>Experiance in year: <span id="demo"></span></p>
                    </div>
                </div> -->
                <div class="submit-btn">
                    <button type="submit" class="btn-submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>

{% else %}

<section class="image-back">
    <div class="form-heading">
        <h2>Post your job</h2>
    </div>

    <div class="skill-content job">
        <div>
            <div class="choose-skill">
                {% if form.errors %}
                <span style="color: red;">{{form.skills.errors}}</span>
                {% endif %}

                <h3>Choose the below skills:</h3>
                <div class="row skills">
                    <div class="col-md-12 col-sm-12 col-xs-12 list-img">
                        <form action="{% url 'jobs:post_job' type.slug %}" method="post">
                            {% csrf_token %}

                            {% for skill in skills %}
                            {% if skill.job_type_id == type.id %}

                            <div class="form-check">
                                <input type="checkbox" name="skills" id="skill-{{skill.id}}" value="{{skill.id}}">

                                <label for="skill-{{ skill.id }}">{{skill.title}}</label>


                            </div>
                            {% endif %}
                            {% endfor %}
                            <span class="other"><i class="fas fa-angle-right"></i><a href="#popup1">Others</a></span>

                    </div>
                </div>
            </div>


            <div class="facility-all">
                {% if form.errors %}
                <span style="color: red;">{{form.facility.errors}}</span>
                {% endif %}

                <div class="facility">
                    <h3>Choose the facilities below:</h3>
                    {% for facility in facilities %}
                    {% if facility.job_type_id == type.id %}
                    <div class="form-check">
                        <input type="checkbox" name="facility" id="id_category" value="{{ facility.id }}">
                        <label for="facility-{{facility.id}}"
                            id="id_category"> {{ facility.title }}</label>
                    </div>
                    {% endif %}
                    {% endfor %}

                    <span class="other"><i class="fas fa-angle-right"></i><a href="#popup2">Others</a></span>
                </div>

                <div class="row facilities">
                    <div class="form-input">

                        <select name="user" required class="form-control" style="display:none;">
                            <option value="{{user.id}}">{{user.username}}</option>
                        </select>

                    </div>
                    <div class="form-input">
                        <select name="job_type" class="form-control" required style="display:none;">
                            <option value="{{type.id}}">{{type.title}}</option>
                        </select>
                    </div>


                    {% if form.errors %}

                    <span style="color: red;">{{form.salary.errors}}</span>

                    {% endif %}
                    <div class="form-input">
                        <label>Salary (in Rs.)</label>
                        <input type="number" name="salary" class="form-control" {% if form.salary.value %}
                            value='{{form.salary.value}}' {% endif %}>
                    </div>

                    {% if form.errors %}

                    <span style="color: red;">{{form.working_time.errors}}</span>

                    {% endif %}

                    <div class="form-input">
                        <label>Office time (From-To)</label>
                        <div class="row">
                            <div class="col-md-6">
                                <input type="text" name="working_time" class="form-control"
                                    {% if form.working_time.value %} value='{{form.working_time.value}}' {% endif %}>
                            </div>
                        </div>
                    </div>


                    {% if form.errors %}

                    <span style="color: red;">{{form.number_of_employee.errors}}</span>

                    {% endif %}

                    <div class="form-input">
                        <label>Number of Employees Required</label>
                        <div class="row">
                            <div class="col-md-6">
                                <input type="number" min="1" name="number_of_employee" class="form-control"
                                    {% if form.number_of_employee.value %} value='{{form.number_of_employee.value}}'
                                    {% endif %}>
                            </div>
                        </div>
                    </div>


                    {% if form.errors %}

                    <span style="color: red;">{{form.number_of_employee.errors}}</span>

                    {% endif %}

                    <div class="form-input">
                        <label>Location</label>
                        <input type="text" name="location" class="form-control" {% if form.location.value %}
                            value='{{form.location.value}}' {% endif %} required>
                    </div>
                </div>
            </div>

            <!-- <div class="experiance red">
                <h3> Experience you require. (In years)</h3>
                <div class="slidecontainer">
                    <input type="range" name="experience" min="1" max="10" value="1" class="slider" id="range">
                    <p>Experiance in year: <span id="demo"></span></p>
                </div>
            </div> -->
            <div class="submit-btn">
                <button type="submit" class="btn-submit">Submit</button>
            </div>
            </form>
        </div>
    </div>
    {% endif %}



    <div id="popup1" class="overlay">
        <div class="popup">
            <h4>Please enter the prefer skills</h4>
            <a class="close" href="#">&times;</a>
            <div class="popup-content">
                <form action="{% url 'jobs:add_skill' %}" method="POST">
                    {% csrf_token %}
                    <select name="job_type" class="form-control" required style="display:none;">
                        <option value="{{type.id}}">{{type.title}}</option>
                    </select>

                    {% if form.errors %}
                    <div class="alert alert-danger">
                        {{form.title.errors}}
                    </div>
                    {% endif %}

                    <textarea name="title" required></textarea>
                    <div class="more-btn"><button type="submit">Add</a></div>
                </form>
            </div>
        </div>
    </div>


    <div id="popup2" class="overlay">
        <div class="popup">
            <h4>Please enter the prefer facility</h4>
            <a class="close" href="#">&times;</a>

            <div class="popup-content">
                <form action="{% url 'jobs:add_facility' %}" method="POST">
                    {% csrf_token %}
                    <select name="job_type" class="form-control" required style="display:none;">
                        <option value="{{type.id}}">{{type.title}}</option>
                    </select>

                    {% if form.errors %}
                    <div class="alert alert-danger">
                        {{form.title.errors}}
                    </div>
                    {% endif %}

                    <textarea name="title" required></textarea>
                    <div class="more-btn"><button type="submit">Add</a></div>
                </form>
            </div>
        </div>
    </div>



</section>
<script>
    $(document).ready(function () {
        var $facilityForm = $('#facility-form')
        $facilityForm.submit(function (event) {
            event.preventDefault()
            event.stopPropagation()
            var $formData = $(this).serialize()
            var $thisURL = $facilityForm.attr('data-url')
            $.ajax({
                method: "POST",
                url: $thisURL,
                data: $formData,
                success: handleFormSuccess,

            });

        });

        function handleFormSuccess(data, textStatus, jqXHR) {
            $("#id_category").append(new Option(data.id, data.title));

            $('#id_category').val(data.id);
            $("#id_category").html(data);
            $('#popup2').modal('toggle');
            console.log(data)


            // $categoryForm.reset(); // reset form data
        }

    });
</script>

{% endif %}
{% endblock %}

backend/templates/jobs/job_list.html
{% extends 'jobs/index.html' %}
{% load static %}
{% load bootstrap3 %}
{% block title %}{% endblock %}

{% block content %}


{% if user.is_authenticated %}



<div class="text-center" id="alert_message">
	{% bootstrap_messages %}
</div>

<section class="newsfeed">

	<div class="container">
		<div class="news-add">
			{% if user.profile.user_type == 'Job Seeker' %}
			<div class="add-button"><a href="{% url 'jobs:apply_job' type.slug  %}">Apply for job</a></div>
			{% else %}
			<div class="add-button"><a href="{% url 'jobs:post_job' type.slug  %}">Post your job</a></div>
			{% endif %}
		</div>
	</div>
	<div class="news-content">
		{% if user.profile.user_type == 'Job Seeker' %}

		<h3>Employer list</h3>
		{% for posted_job in posted_jobs %}
		{% if posted_job.job_type_id == type.id %}
		<div class="jobseeker-list">
			<div class="js-title">Job posted <span class="location-symbol">@</span> <span
					class="list-name">{{ posted_job.location }}</span></div>
			<div class="jsv-btn"><a href="{% url 'jobs:posted_job_detail' type.slug posted_job.id %}">View</a></div>
		</div>
		{% endif %}
		{% endfor %}

		{% else %}
		<h3>Job seekers list</h3>

		{% for applied_job in applied_jobs %}
		{% if applied_job.job_type_id == type.id %}
		<div class="jobseeker-list">
			<div class="js-title">Applied by: <span class="list-name">{{ applied_job.user.username }}</div>
			<div class="jsv-btn"><a href="{% url 'jobs:applied_job_detail' type.slug applied_job.id  %}">View</a>
			</div>
		</div>
		{% endif %}
		{% endfor %}

		{% endif %}
	</div>
</section>





{% endif %}
{% endblock %}

backend/templates/jobs/main.html
{% extends 'jobs/index.html' %} {% load static %} {% block content%}
<section class="job-all">
  <div class="container">
    <div class="job-title">
      <h1>Browse Jobs</h1>
    </div>
    <div class="job-categories">
      <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
          <a href="{% url 'jobs:dashboard' %}">
            <div class="job-category red">
              <div class="job-cross"></div>
              <div class="job-icon">
                <i class="fas fa-universal-access"></i>
              </div>
              <div class="job-title">Job</div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
          <a href="eskill.html">
            <div class="job-category green">
              <div class="job-cross"></div>
              <div class="job-icon"><i class="fas fa-book-open"></i></div>
              <div class="job-title">Book</div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
          <a href="eskill.html">
            <div class="job-category blue">
              <div class="job-cross"></div>
              <div class="job-icon"><i class="fas fa-home"></i></div>
              <div class="job-title">House</div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
          <a href="{% if user.is_authenticated %}
          {% if user.profile.user_type == 'Job Seeker' %}
          {% url 'land:landformbuy' %}
          {% else %}
          {% url 'land:landformsell' %}
          {% endif %}
          {% else %}
          {% url 'users:login_user' %}
          {% endif %}">
            <div class="job-category green">
              <div class="job-cross"></div>
              <div class="job-icon"><i class="fas fa-vector-square"></i></div>
              <div class="job-title">Land</div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
          <a href="{% url 'room:roomtype' %}">
            <div class="job-category blue">
              <div class="job-cross"></div>
              <div class="job-icon"><i class="fas fa-landmark"></i></div>
              <div class="job-title">Room</div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
          <a href="eskill.html">
            <div class="job-category red">
              <div class="job-cross"></div>
              <div class="job-icon">
                <i class="fas fa-chalkboard-teacher"></i>
              </div>
              <div class="job-title">Others</div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

backend/templates/jobs/match.html
{% for i in match %}

{{i}}

{% endfor %}